### ISSUE TITLE
compiled?

### ISSUE THREAD

**Issue by mte0** [MarcusSlover/GodBridging#2]
hey dude, just wondering if you could release a compiled jar of this, I don't know much abt java so yeah. Discord: ProxyBlade#0001

**Comment by MarcusSlover** [comment]
Hello,
The compiled plugin-jar is here: https://github.com/MarcusSlover/GodBridging/releases/tag/v1.0
Just saying, this is a plugin and not a modification to your client. You can upload it on your Minecraft server (1.8.9) and run /gb to speed bridge. When enabled you will be placing blocks below you extremely fast.

Best regards,
Marcus.
